title: Stevens Adventure
author: Steven Han
email: sahiagb@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am Steven Han and I am a cool person.
# social links
instagram_username: @believe_in_stevenh # DO NOT include the @ character, or else the build will fail!
github_username:  majikyouser # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
