---
title: "MyBlog"
date: 2021-05-23
---
title: Stevens Adventure
author: Steven Han
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I am Steven Han and I am a cool person.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
